### ISSUE TITLE
ProtocolLib bug when a player is getting flagged or kicked

### ISSUE THREAD

**Issue by TheFates123** [Seveningful/BayMaxAC#15]
When a player is getting flagged or kicked . A bug was showed in the console and some "ProtocolLib things" appeared in that.
- Spigot version : TacoSpigot 1.8.8
- ProtocolLib version : 4.2.0

> [00:29:49 ERROR]: [Baymax] Unhandled exception occured in onPacketReceiving(PacketEvent) for Baymax
java.lang.NullPointerException
        at eu.gurudev.baymax.b.a.onPacketReceiving(a.java:42) ~[Baymax-Alpha-042.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib%20(10).jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib%20(10).jar:4.2.0]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib%20(10).jar:4.2.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [TacoSpigot-1.8.8-latest.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[00:29:50 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@75cb7996[
    a=110
    action=ATTACK
    c=<null>
  ]

**Comment by Seveningful** [comment]
I see,
This happens because some tasks are asynchronous. I'll fix this for the next version ( Alpha-06 )
