### ISSUE TITLE
Console Spam (Caused by: java.lang.NullPointerException)

### ISSUE THREAD

**Issue by MPGxxYT** [Seveningful/BayMaxAC#52]
The console is just gets spammed with this, and I don't know why.

**=========================================================**
04.11 17:07:15 [Server] INFO Caused by: java.lang.NullPointerException
04.11 17:07:15 [Server] INFO at java.lang.Thread.run(Thread.java:745)
04.11 17:07:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04.11 17:07:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04.11 17:07:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
04.11 17:07:15 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Baymax vAlpha-101 generated an exception while executing task 62
04.11 17:07:15 [Server] WARN Exception in thread "pool-3-thread-82" 
**=========================================================**

**Comment by Seveningful** [comment]
Can't really tell where it's coming from since the error isn't complete,
Still, i'll try to fix it
